version: "3"
services:
  app:
    build: 
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - app_network
    restart: always
  api:
    build: 
      context: ./api
      dockerfile: ./Dockerfile
    volumes:
      - ./api/database:/api/database:rw
      - ./api/public/uploads:/api/public/uploads:rw
    ports:
      - 1337:1337
    networks:
      - app_network
    restart: always
  award-app:
    build: 
      context: ./award-app
      dockerfile: ./Dockerfile
    ports:
      - 8181:8181
    networks:
      - app_network
    restart: always
  award-api:
    build: 
      context: ./award-api
      dockerfile: ./Dockerfile
    volumes:
      - ./award-api:/var/www/html:rw
    ports:
      - 8282:8282
    networks:
      - app_network
    restart: always
  database:
    image: mysql:8.0.35
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./database:/var/lib/mysql:rw
    ports:
      - 3306:3306
    networks:
      - app_network
    restart: always
networks:
  app_network:
    driver: bridge
